INSERT INTO book (id, title, author, isbn) VALUES (1, 'Clean Code', 'Robert C. Martin', '978-0132350884');
INSERT INTO book (id, title, author, isbn) VALUES (2, 'Effective Java', 'Joshua Bloch', '978-0134685991');
INSERT INTO book (id, title, author, isbn) VALUES (3, 'Design Patterns', 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides', '978-0201633610');
INSERT INTO book (id, title, author, isbn) VALUES (4, 'Refactoring', 'Martin Fowler', '978-0201485677');
INSERT INTO book (id, title, author, isbn) VALUES (5, 'The Pragmatic Programmer', 'Andrew Hunt, David Thomas', '978-0201616224');
INSERT INTO book (id, title, author, isbn) VALUES (6, 'Head First Design Patterns', 'Eric Freeman, Bert Bates, Kathy Sierra, Elisabeth Robson', '978-0596007126');
INSERT INTO book (id, title, author, isbn) VALUES (7, 'Java Concurrency in Practice', 'Brian Goetz', '978-0321349606');
INSERT INTO book (id, title, author, isbn) VALUES (8, 'Test Driven Development', 'Kent Beck', '978-0321146533');
INSERT INTO book (id, title, author, isbn) VALUES (9, 'Working Effectively with Legacy Code', 'Michael Feathers', '978-0131177055');
INSERT INTO book (id, title, author, isbn) VALUES (10, 'Clean Architecture', 'Robert C. Martin', '978-0134494164');

INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (1, 'Alice', 'Great book on clean coding practices.', 5, 1);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (2, 'Bob', 'A must-read for Java developers.', 4, 2);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (3, 'Charlie', 'Excellent introduction to design patterns.', 5, 3);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (4, 'David', 'Refactoring is a fundamental skill.', 5, 4);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (5, 'Eve', 'Pragmatic and useful advice for programmers.', 5, 5);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (6, 'Frank', 'Great patterns explained in an easy way.', 5, 6);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (7, 'Grace', 'Concurrency made understandable.', 5, 7);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (8, 'Heidi', 'TDD is essential for good software development.', 5, 8);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (9, 'Ivan', 'Legacy code management is crucial.', 5, 9);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (10, 'Judy', 'Clean architecture principles are well presented.', 5, 10);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (11, 'Alice', 'Must-read for every programmer.', 5, 1);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (12, 'Bob', 'Great tips and techniques.', 4, 5);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (13, 'Charlie', 'Design patterns are crucial.', 5, 6);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (14, 'David', 'Very helpful book.', 4, 7);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (15, 'Eve', 'A must-read for software architects.', 5, 10);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (16, 'Frank', 'Good book for understanding TDD.', 4, 8);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (17, 'Grace', 'Well written and informative.', 5, 3);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (18, 'Heidi', 'Practical advice on legacy code.', 5, 9);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (19, 'Ivan', 'Refactoring is essential.', 5, 4);
INSERT INTO review (id, reviewer_name, content, rating, book_id) VALUES (20, 'Judy', 'Great book on clean code.', 5, 1);
